<?php

namespace App\Serializer;

use Symfony\Component\Messenger\Envelope;
use Symfony\Component\Messenger\Transport\Serialization\Serializer;

class EventSerializer extends Serializer
{
    public function encode(Envelope $envelope): array
    {
        return parent::encode($envelope); // TODO: Change the autogenerated stub
    }
}